name: build

on:
    push:
        branches: [ master ]

jobs:
    build:
        name: build

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build and publish
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  name: tonybogdanov/zip
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
